Repository openshift-pipelines/pipelines-as-code, pull requests merged in 2025-05, with the labels that each got.

#2053 fix: update concurrency group expression in e2e workflow
  .github/workflows/e2e.yaml
Labels: e2e

#2066 Disable GitLab comments for pipeline start/end events to reduce MR noise
  config/300-repositories.yaml
  docs/content/docs/guide/repositorycrd.md
  pkg/apis/pipelinesascode/v1alpha1/types.go
  pkg/provider/gitlab/gitlab.go
  pkg/reconciler/status_test.go
  pkg/webhook/validation.go
  test/gitlab_delete_tag_event_test.go
  test/gitlab_incoming_webhook_test.go
  test/gitlab_merge_request_test.go
  test/gitlab_push_gitops_command_test.go
  test/pkg/gitlab/crd.go
  test/pkg/options/options.go
  test/pkg/repository/update.go
Labels: e2e

#2077 chore: Vale rules enforcing GitLab
  .vale/styles/RedHat/CaseSensitiveTerms.yml
  .vale/styles/RedHat/GitLinks.yml
  .vale/styles/RedHat/HeadingPunctuation.yml
  .vale/styles/RedHat/Hyphens.yml
  .vale/styles/RedHat/SimpleWords.yml
  .vale/styles/RedHat/Spelling.yml
  .vale/styles/RedHat/TermsErrors.yml
  .vale/styles/RedHat/TermsSuggestions.yml
  .vale/styles/RedHat/TermsWarnings.yml
  .vale/styles/RedHat/Using.yml
  Makefile
  docs/content/docs/guide/matchingevents.md
  docs/content/docs/install/kubernetes.md
  pkg/adapter/adapter.go
  pkg/params/info/events.go
  pkg/provider/gitlab/README.md
  pkg/provider/gitlab/detect.go
  pkg/provider/gitlab/gitlab.go
  pkg/provider/gitlab/gitlab_test.go
  pkg/provider/gitlab/parse_payload.go
  pkg/provider/gitlab/parse_payload_test.go
  pkg/reconciler/event.go
Labels: gitlab, e2e

#2079 chore: Separate CI log formatting into dedicated workflow step
  .github/workflows/e2e.yaml
  hack/gh-workflow-ci.sh
Labels: e2e

#2081 ci: Add conventional commit check to Tekton linter
  .tekton/linter.yaml
Labels: ci

#2099 chore: Update controller finalizer name to include explicit part
  pkg/action/patch_test.go
  pkg/apis/pipelinesascode/register.go
  pkg/pipelineascode/pipelineascode_test.go
  pkg/provider/gitlab/gitlab.go
  pkg/reconciler/controller.go
  pkg/reconciler/controller_test.go
Labels: fix

#2102 chore: Change scmClient to client in Bibtucket Data Center
  pkg/provider/bitbucketdatacenter/acl.go
  pkg/provider/bitbucketdatacenter/acl_test.go
  pkg/provider/bitbucketdatacenter/bitbucketdatacenter.go
  pkg/provider/bitbucketdatacenter/bitbucketdatacenter_test.go
Labels: refactoring

#2100 feat: Add JSON body support for incoming webhook parameters
  docs/content/docs/guide/incoming_webhook.md
  pkg/adapter/incoming.go
  pkg/adapter/incoming_test.go
  test/github_incoming_test.go
  test/gitlab_incoming_webhook_test.go
Labels: feature
